ALTER TABLE Student ADD CONSTRAINT CheckStudentAge CHECK (age >= 16);

ALTER TABLE Student ADD CONSTRAINT UniqueStudentName UNIQUE (name);

ALTER TABLE Student ALTER COLUMN name SET NOT NULL;

ALTER TABLE Faculty ADD CONSTRAINT UniqueFacultyNameColor UNIQUE (name, color);

ALTER TABLE Student ALTER COLUMN age SET DEFAULT 20;